apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

# namespace to deploy all Resources to
namespace: andrea-nsprod

# labels added to all Resources
commonLabels:
  app: webapp

patches:
- path: deployment_patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: webapp
